### ISSUE TITLE
R2 - Dataflow Diagram

### ISSUE THREAD

**Issue by CallanVass** [CallanVass/Talent-Forge-Front-End#1]
Dataflow Diagram

RUBRIC:

CMP1043-4.2 Dataflow Diagram

MARKING:

Provides dataflow diagram(s) that strictly follow the standard conventions to clearly identify the processes within your application. Clearly depicts where data is coming from, where it is going and how it is being stored.

**Comment by Matt-bryant21** [comment]
Dataflow Diagrams created and added to markdown with explainers
