### ISSUE TITLE
Build Login Page Component

### ISSUE THREAD

**Issue by CallanVass** [CallanVass/Talent-Forge-Front-End#50]
Things to remember:

- Create a new component for reusable features
- Create dummy data within components for current development stage
- One thing at a time
- Have fun (OR ELSE!)

**Comment by krd81** [comment]
- [x] Colours/Styling
- [x] Login button
- [x] TalentForce logo
- [x] Navigates to home
- [ ] Dummy data to test logic
- [ ] How to disable nav bar??

**Comment by krd81** [comment]
Is this page responsive for different screen sizes?
